name: Release-Please
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release-please:
    name: Release-Please
    runs-on: ubuntu-latest
    steps:
      - id: manifest
        name: Release-Please from Manifest
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}